# Generated by Django 4.2.5 on 2023-12-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10, unique=True)),
                ('parent_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('course', models.CharField(choices=[('MCA', 'MCA'), ('MBA', 'MBA'), ('MMH', 'MMH'), ('MA', 'MA'), ('MSW', 'MSW'), ('MCMS', 'MCMS')], max_length=4)),
                ('date_of_birth', models.DateField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('student_image', models.ImageField(upload_to='students/images/')),
                ('roll_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
